on:
  push:
    branches:
      - main
  pull_request:  
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch workflow in other repo
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: dispatch-event
        client-payload: '{ "github": ${{ toJson(github) }}}'
