on:
  push:
    branches:
      - main
  pull_request:  
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Dispatch workflow in other repo
      run: |
        curl -XPOST -u "${{ github.actor }}:${{ secrets.PASSWORD }}" \
         -H "Accept: application/vnd.github.everest-preview+json" \
         -H "Content-Type: application/json" \
         https://api.github.com/repos/Sreesanth46/coverage-notfication/dispatches --data '{"event_type": "build_application"}
